# Generated by Django 5.0.6 on 2024-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='experience',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
