# Generated by Django 5.0.6 on 2024-06-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app8', '0002_alter_item_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('age', models.PositiveBigIntegerField()),
                ('designation', models.CharField(max_length=225)),
                ('salary', models.PositiveBigIntegerField()),
                ('experience', models.CharField(max_length=225, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
